### ISSUE TITLE
twitter_last_read.user.js: Update for new twitter UI

### ISSUE THREAD

**Issue by Niamor** [ArmEagle/userscripts#5]
Hello, I have been using this script for many years now and find it super useful if not mandatory for how I browse twitter, thanks for it.
Few weeks ago Twitter started rolling out their new interface, I've been looking for updates to this script ever since and nothing so decided to finally ask if you will consider update it?
I know that add-ons and others scripts allow to use the old interface which I'm guessing should still work with this script even though I haven't tried it but I'd like to avoid doing this if possible.

Thank you very much.

**Comment by ArmEagle** [comment]
Hello!

I honestly didn't know there was still a version of the Twitter website that's this script still worked on.
I have been using mobile.twitter.com for well over a year now. Mostly because it's faster on my older laptop.

The structure of the elements on that version is more complex. There are no human readable classnames anymore. I have thought about rewriting this script since I switched. But it always seemed like such an arduousness task that I never really got into it.

So, yes I have considered. And I really should. And then finally also add some way to share the 'last read' between devices. But I'm still not there yet.

What are you using most though. Just the scroll to last read? Or also some of the other small 'hidden' features.
And in what browser are you using it?

By the way. I'm using the Explore functionality on the mobile website now, with some filters set. That way I always keep the "Latest tweets" order, and filter out some of the ways Twitter is forcing tweets on you (promoted, and likes, by friends of friends, or whatever). That's this url:
https://mobile.twitter.com/search?q=filter%3Afollows%20-filter%3Areplies%20include%3Anativeretweets&src=typed_query&f=live

**Comment by Maryse47** [comment]
This script still works on old twitter interface which can be used by forging user-agent. For the twits order it's best to use list.

**Comment by Niamor** [comment]
Hello, thanks for replying.

@ArmEagle I am/was only using the scroll to last read and being able to mark as read, didn't know of other "hidden" features. I use Firefox Nightly.
I just really like to browse from bottom to top instead of top from bottom like Twitter forces you to, I remember when Twitter use to show which tweet you last read and when they removed it I found your script.

@Maryse47 Thought so it would work but I'd like avoid doing that if possible as I don't mind the new interface like others might and the fact that it will most likely be deprecated and already read issues with people using it.

**Comment by ArmEagle** [comment]
@Maryse47 Ok. At first glance it looks like twitter.com is now similar to mobile.twitter.com.

@Niamor Check. That's what I used most myself too. From old to new makes so much more sense. Though nowadays with threads it's sometimes a bit tricky.

I've made a tiny start yesterday. Maybe I'll get somewhere this weekend. Maybe it will take much longer.

**Comment by Maryse47** [comment]
Twitter disabled old UI so this script stopped working anywhere :cry:

**Comment by ArmEagle** [comment]
@Maryse47  I know. Several people found me on Twitter (same name as here) already.

I have made a start at some point. But the new ReactJS website is a bit of a pain.

I should try and look into it again.

**Comment by Maryse47** [comment]
Great. Hopefully it will work on mobile version too. I don't know if it help but here's some other userscript that work on new site: https://github.com/Bl4Cc4t/GoodTwitter2 . Maybe you'll find something useful there.

**Comment by ArmEagle** [comment]
I've uploaded what I'm currently working on at https://github.com/ArmEagle/TwitterLastRead .
Still need to cleanup and add/change several things. See todo list in src/main.js.

Closing this issue now.
